logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /opt/app/logs/access.log
      record_log_file_path: true
  processors:
    set-timestamp:
      type: parse_json
      time_key: date
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [set-timestamp, move_severity]