# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: express app

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    env: 
        DATABASE_URL: mysql://root:test@localhost:3306/Test_DB
        
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'Test_DB'
          mysql root password: 'test'

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Migrate Database
        run: npm run prisma-migrate
        
      - name: Run testing
        run: npm run test
