name: "packer-ci"

on:
  pull_request:
   branches:
    - main
   paths:
    - 'packer/**'

jobs: 
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v4
    
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
    
      - name: "Run Packer fmt"
        run: |
            if ! packer fmt --check packer/.; then
            echo "Packer fmt found formatting issues. Please run 'packer fmt' locally and commit the changes."
            exit 1
            fi
    
      - name: "Run Packer validate"
        run: |
          if ! packer validate packer/.; then
          echo "Packer validation failed. Please fix the issues and try again."
          exit 1
          fi
